'\" t
.\"     Title: modhex
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: Version 1.13
.\"    Manual: YubiKey C Library Manual
.\"    Source: yubico-c
.\"  Language: English
.\"
.TH "MODHEX" "1" "Version 1\&.13" "yubico\-c" "YubiKey C Library Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
modhex \- convert data to/from modhex encoding
.SH "SYNOPSIS"
.sp
\fBmodhex\fR [\-d] [\-h] \fIDATA\fR
.SH "DESCRIPTION"
.sp
Encode/decode modhex data \fIDATA\fR to binary and hex\&.
.SH "OPTIONS"
.sp
The string DATA is the data to convert\&.
.PP
\fB\-d\fR
.RS 4
Decode data (the default is to encode data)\&.
.RE
.PP
\fB\-h\fR
.RS 4
Use hex encoding for all non\-modhex data\&.
.RE
.SH "EXAMPLES"
.sp
ModHex encode ASCII\-string "test":
.sp
.if n \{\
.RS 4
.\}
.nf
modhex test
.fi
.if n \{\
.RE
.\}
.sp
Decode ModHex data "ifhgieif" into ASCII string:
.sp
.if n \{\
.RS 4
.\}
.nf
modhex \-d ifhgieif
.fi
.if n \{\
.RE
.\}
.sp
ModHex encode hex\-encoded data "b565716f":
.sp
.if n \{\
.RS 4
.\}
.nf
modhex \-h b565716f
.fi
.if n \{\
.RE
.\}
.sp
Decode ModHex data "nghgibhv" and print hex\-encode data:
.sp
.if n \{\
.RS 4
.\}
.nf
modhex \-d \-h nghgibhv
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
YubiKeys can be obtained from Yubico: http://www\&.yubico\&.com/
