'\" t
.\"     Title: ykparse
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: Version 1.13
.\"    Manual: YubiKey C Library Manual
.\"    Source: yubico-c
.\"  Language: English
.\"
.TH "YKPARSE" "1" "Version 1\&.13" "yubico\-c" "YubiKey C Library Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ykparse \- decrypt and show information inside a YubiKey OTP
.SH "SYNOPSIS"
.sp
\fBykparse\fR \fIAESKEY\fR \fITOKEN\fR
.SH "DESCRIPTION"
.sp
Decrypt and display information inside a YubiKey OTP\&.
.SH "OPTIONS"
.PP
\fBAESKEY\fR
.RS 4
The 16\-character AES\-128 key to use in hex\&.
.RE
.PP
\fBTOKEN\fR
.RS 4
The modhex encoded One\-Time Password (OTP)\&.
.RE
.SH "EXAMPLES"
.sp
Typical usage of the tool is as follows\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ykparse ecde18dbe76fbd0c33330f1c354871db dteffujedcflcindvdbrblehecuitvjkjevvehjd
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.sp
YubiKeys can be obtained from Yubico: http://www\&.yubico\&.com/
